"""Add initial data for breeds and kittens

Revision ID: 74e96238edf1
Revises: 1a3027bcee4d
Create Date: 2024-10-02 02:13:00.503388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from src.models import Kitten, Breed

# revision identifiers, used by Alembic.
revision: str = '74e96238edf1'
down_revision: Union[str, None] = '1a3027bcee4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind)

    # Создание пород
    siamese = Breed(name='Siamese')
    persian = Breed(name='Persian')
    sphynx = Breed(name='Sphynx')

    # Добавление пород в сессию и коммит
    session.add_all([siamese, persian, sphynx])
    session.commit()

    # Получение ID для пород
    siamese_id = siamese.id
    persian_id = persian.id
    sphynx_id = sphynx.id

    # Создание котят
    kitten1 = Kitten(breed_id=siamese_id, color='White', age=5, description='Very playful and active')
    kitten2 = Kitten(breed_id=persian_id, color='Black', age=7, description='Calm and quiet')
    kitten3 = Kitten(breed_id=sphynx_id, color='Pink', age=3, description='Friendly and curious')

    # Добавление котят в сессию и коммит
    session.add_all([kitten1, kitten2, kitten3])
    session.commit()

    # Закрытие сессии
    session.close()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind)

    session.execute(
        "DELETE FROM kittens WHERE description IN ('Very playful and active', 'Calm and quiet', 'Friendly and curious')")
    session.execute("DELETE FROM breeds WHERE name IN ('Siamese', 'Persian', 'Sphynx')")

    session.commit()
    session.close()
    # ### end Alembic commands ###
